"""State and structured models for Cover Letter Agent."""

from __future__ import annotations

import json
from typing import Literal, TypedDict

from pydantic import BaseModel, Field

from app.schemas.job_description_parser import (
    ParsedJobDescription,
)
from app.schemas.resume_matching import (
    ResumeJobMatchResult,
)
from app.schemas.resume_parsing import (
    ResumeStructuredContent,
)

CoverLetterTone = Literal[
    "professional",
    "confident",
    "concise",
]

CoverLetterStatus = Literal[
    "pending",
    "preparing",
    "generating",
    "validating",
    "retrying",
    "completed",
    "completed_with_fallback",
    "failed",
]


class CoverLetterEvidence(BaseModel):
    """Resume evidence supporting a cover-letter claim."""

    claim: str = Field(min_length=1)
    resume_excerpt: str = Field(min_length=1)
    source_section: str = Field(min_length=1)


class CoverLetterAnalysis(BaseModel):
    """Structured output generated by Groq."""

    greeting: str = Field(min_length=1)
    opening_paragraph: str = Field(min_length=1)
    body_paragraphs: list[str] = Field(
        min_length=1,
        max_length=4,
    )
    closing_paragraph: str = Field(min_length=1)
    sign_off: str = Field(min_length=1)

    skills_mentioned: list[str] = Field(default_factory=list)

    evidence: list[CoverLetterEvidence] = Field(default_factory=list)

    warnings: list[str] = Field(default_factory=list)

    rationale: str = Field(min_length=1)

    def full_text(self) -> str:
        """Return the complete cover letter."""

        parts = [
            self.greeting,
            "",
            self.opening_paragraph,
            "",
            *[f"{paragraph}\n" for paragraph in self.body_paragraphs],
            self.closing_paragraph,
            "",
            self.sign_off,
        ]

        return "\n".join(parts).strip()


class CoverLetterRequest(BaseModel):
    """Input required by the Cover Letter Agent."""

    resume: ResumeStructuredContent
    job_description: ParsedJobDescription
    match_result: ResumeJobMatchResult

    resume_raw_text: str = ""

    candidate_name: str | None = Field(
        default=None,
        max_length=120,
    )

    company_context: str | None = Field(
        default=None,
        max_length=4000,
    )

    tone: CoverLetterTone = "professional"

    max_words: int = Field(
        default=300,
        ge=150,
        le=500,
    )


class CoverLetterAgentInput(BaseModel):
    """Prompt input for the Cover Letter Agent."""

    request: CoverLetterRequest
    validation_feedback: list[str] = Field(default_factory=list)

    def to_prompt_payload(self) -> dict[str, str]:
        """Convert request to prompt variables."""

        feedback = (
            "\n".join(f"- {message}" for message in self.validation_feedback)
            or "No validation feedback is available."
        )

        return {
            "resume_json": json.dumps(
                self.request.resume.model_dump(mode="json"),
                indent=2,
                sort_keys=True,
            ),
            "resume_raw_text": (self.request.resume_raw_text or "No additional raw resume text."),
            "job_description_json": json.dumps(
                self.request.job_description.model_dump(mode="json"),
                indent=2,
                sort_keys=True,
            ),
            "match_result_json": json.dumps(
                self.request.match_result.model_dump(mode="json"),
                indent=2,
                sort_keys=True,
            ),
            "candidate_name": (self.request.candidate_name or "Candidate name not supplied"),
            "company_context": (self.request.company_context or "No additional company context."),
            "tone": self.request.tone,
            "max_words": str(self.request.max_words),
            "validation_feedback": feedback,
        }


class CoverLetterResult(BaseModel):
    """Final validated cover-letter result."""

    target_role: str | None = None
    company_name: str | None = None

    greeting: str
    opening_paragraph: str
    body_paragraphs: list[str]
    closing_paragraph: str
    sign_off: str

    full_text: str

    skills_mentioned: list[str] = Field(default_factory=list)

    evidence: list[CoverLetterEvidence] = Field(default_factory=list)

    warnings: list[str] = Field(default_factory=list)

    agent_name: str = "groq_cover_letter_agent"
    agent_version: str = "1.0.0"

    deterministic_fallback: bool = False


class CoverLetterState(
    TypedDict,
    total=False,
):
    """Shared LangGraph state."""

    request: CoverLetterRequest
    agent_result: CoverLetterAnalysis | None
    final_result: CoverLetterResult | None

    attempt_count: int
    max_attempts: int

    validation_errors: list[str]
    warnings: list[str]

    status: CoverLetterStatus
    last_error: str | None


class CoverLetterWorkflowResult(BaseModel):
    """Final workflow execution result."""

    status: CoverLetterStatus

    cover_letter: CoverLetterResult | None = None
    agent_analysis: CoverLetterAnalysis | None = None

    attempt_count: int = 0

    warnings: list[str] = Field(default_factory=list)

    validation_errors: list[str] = Field(default_factory=list)

    last_error: str | None = None
